// exporter.js — Circuit → C#, Lua, Python, JavaScript, GDScript, Pseudocode

const Exporter = (() => {

  function export_(lang) {
    const { nodes, wires } = Canvas.getCircuitData();
    if (!nodes.length) return comment(lang, 'Empty circuit — add chips to the canvas first.');
    const ctx = buildCtx(nodes, wires);
    switch (lang) {
      case 'csharp':     return toCSharp(ctx);
      case 'lua':        return toLua(ctx);
      case 'python':     return toPython(ctx);
      case 'javascript': return toJS(ctx);
      case 'gdscript':   return toGDS(ctx);
      case 'pseudocode': return toPseudo(ctx);
      case 'roblox':     return toRoblox(ctx);
      case 'unity':      return toUnity(ctx);
      case 'unreal':     return toUnreal(ctx);
      default:           return '// Unknown language';
    }
  }

  function fileExtension(lang) {
    return { csharp:'cs', lua:'lua', python:'py', javascript:'js', gdscript:'gd',
             pseudocode:'txt', roblox:'lua', unity:'cs', unreal:'cpp' }[lang] || 'txt';
  }
  function engineInfo(lang) {
    return {
      roblox: { name:'Roblox Studio', folder:'ServerScriptService', file:'Circuit.lua',  hint:'Place in ServerScriptService. Requires Roblox Studio open.' },
      unity:  { name:'Unity',         folder:'Assets/Scripts',       file:'Circuit.cs',   hint:'Drop into Assets/Scripts/ in your Unity project.' },
      unreal: { name:'Unreal Engine',  folder:'Source/YourProject',  file:'Circuit.cpp',  hint:'Add to Source folder and include in Build.cs.' },
    }[lang];
  }

  // ── Context builder ──────────────────────────────────────────────────────
  function buildCtx(nodes, wires) {
    const defs = {};
    nodes.forEach(n => { defs[n.id] = { node: n, def: getChipDef(n.chipId) }; });

    const inSrc = {};   // `nodeId.port` → { fromNode, fromPort }
    const outTgt = {};  // `nodeId.port` → [{ toNode, toPort }]
    wires.forEach(w => {
      inSrc[`${w.toNode}.${w.toPort}`] = { fromNode: w.fromNode, fromPort: w.fromPort };
      const k = `${w.fromNode}.${w.fromPort}`;
      if (!outTgt[k]) outTgt[k] = [];
      outTgt[k].push({ toNode: w.toNode, toPort: w.toPort });
    });

    const entries = nodes.filter(n => {
      const d = getChipDef(n.chipId); if (!d) return false;
      return d.inputs.every(p => p.type !== 'exec') && d.outputs.some(p => p.type === 'exec');
    });

    // Variable registry — read cloud/synced from node (user's toggle) not chip def
    const vars = {};
    nodes.forEach(n => {
      const d = getChipDef(n.chipId);
      if (d?.isVariable && n.varName) vars[n.id] = {
        name: n.varName, type: d.varType,
        isCloud:  !!n.isCloud,   // set by checkbox in UI
        isSynced: !!n.isSynced,  // set by checkbox in UI
      };
    });

    return { nodes, defs, inSrc, outTgt, entries, vars };
  }

  // ── Expression helpers ───────────────────────────────────────────────────
  function varOf(nodeId, portIdx) { return `_${nodeId.replace(/-/g,'_')}_o${portIdx}`; }

  function getExpr(ctx, nodeId, portIdx, lang) {
    const key = `${nodeId}.${portIdx}`;
    if (ctx.inSrc[key]) return varOf(ctx.inSrc[key].fromNode, ctx.inSrc[key].fromPort);
    const { node, def } = ctx.defs[nodeId];
    if (!def) return nullVal(lang);
    const port = def.inputs[portIdx];
    if (!port) return nullVal(lang);
    // Variable chip: return var name
    if (def.isVariable) return node.varName || 'myVar';
    const val = node.defaults[`i${portIdx}`] !== undefined ? node.defaults[`i${portIdx}`] : port.default;
    if (port.type === 'bool')   return boolVal(val, lang);
    if (port.type === 'int' || port.type === 'float' || port.type === 'number') return numVal(val);
    if (port.type === 'string') return strVal(val, lang);
    return nullVal(lang);
  }

  function boolVal(v, lang) {
    const b = (v===true||v==='true'||v==='TRUE');
    return (lang==='python'||lang==='gdscript') ? (b?'True':'False') : (b?'true':'false');
  }
  function numVal(v)    { return (v!==undefined&&v!=='') ? String(v) : '0'; }
  function strVal(v, _) { return `"${v||''}"`;  }
  function nullVal(lang) {
    return { python:'None', lua:'nil', gdscript:'null' }[lang] || 'null';
  }
  function comment(lang, s) {
    if (lang==='python'||lang==='gdscript') return `# ${s}`;
    if (lang==='lua') return `-- ${s}`;
    return `// ${s}`;
  }

  // ── Follow exec chain ────────────────────────────────────────────────────
  function follow(ctx, nodeId, outPortIdx, lang, indent, emit, emitFn) {
    const k = `${nodeId}.${outPortIdx}`;
    const targets = ctx.outTgt[k] || [];
    targets.forEach(({ toNode }) => emitFn(ctx, toNode, lang, indent, emit));
  }

  // ═══════════════════════ C# ═══════════════════════════
  function toCSharp(ctx) {
    const lines = [];
    const o = s => lines.push(s);
    o('// Generated by RR Circuits');
    o('using System; using System.Collections; using System.Collections.Generic;');
    o('using UnityEngine;');
    o('');
    o('public class GeneratedCircuit : MonoBehaviour {');

    // Variable declarations
    Object.values(ctx.vars).forEach(v => {
      o(`    private ${csType(v.type)} ${v.name} = ${csDefault(v.type)};`);
      if (v.isCloud) o(`    // ☁ Cloud Variable: ${v.name}`);
      if (v.isSynced) o(`    // 🔄 Synced Variable: ${v.name}`);
    });

    // Declare output variables
    ctx.nodes.forEach(({ id, chipId }) => {
      const d = getChipDef(chipId); if (!d) return;
      d.outputs.forEach((p, i) => { if (p.type !== 'exec') o(`    private ${csType(p.type)} ${varOf(id,i)};`); });
    });

    o('');

    ctx.entries.forEach(node => {
      const d = getChipDef(node.chipId);
      o(`    ${csEvent(node.chipId)} {`);
      const emit = s => lines.push(s);
      emitCS(ctx, node.id, '        ', emit);
      o('    }');
      o('');
    });

    if (!ctx.entries.length) {
      o('    void Update() {');
      const emit = s => lines.push(s);
      ctx.nodes.forEach(n => emitCS(ctx, n.id, '        ', emit));
      o('    }');
    }

    o('}');
    return lines.join('\n');
  }

  function csType(t) {
    return { int:'int', float:'float', number:'float', bool:'bool', string:'string',
      object:'GameObject', player:'GameObject', vector3:'Vector3',
      quaternion:'Quaternion', color_t:'Color', list:'List<object>', any:'object' }[t] || 'object';
  }
  function csDefault(t) {
    return { int:'0', float:'0f', number:'0f', bool:'false', string:'""',
      object:'null', player:'null', vector3:'Vector3.zero', quaternion:'Quaternion.identity',
      color_t:'Color.white', list:'new List<object>()', any:'null' }[t] || 'null';
  }
  function csEvent(id) {
    return { on_init:'void Start()', on_update:'void Update()',
      on_joined:'void OnPlayerJoined(GameObject player)',
      on_left:'void OnPlayerLeft(GameObject player)',
      authority:'bool IsLocalAuthority()' }[id] || `void ${id}_Run()`;
  }

  function emitCS(ctx, nodeId, ind, emit) {
    const { node, def } = ctx.defs[nodeId]; if (!def) return;
    const g = i => getExpr(ctx, nodeId, i, 'csharp');
    const v = i => varOf(nodeId, i);
    const f = (p) => follow(ctx, nodeId, p, 'csharp', ind, emit, emitCS);

    switch (node.chipId) {
      // Control Flow
      case 'authority':  emit(`${ind}bool ${v(2)} = /* IsLocalAuthority check */;`); emit(`${ind}if (${v(2)}) {`); f(0); emit(`${ind}} else {`); f(1); emit(`${ind}}`); break;
      case 'sequence':   f(0); f(1); f(2); f(3); f(4); break;
      case 'delay':      emit(`${ind}yield return new WaitForSeconds(${g(1)});`); f(0); break;
      case 'foreach':    emit(`${ind}foreach (var _item in ${g(1)}) {`); emit(`${ind}    var ${v(2)} = _item;`); f(0); emit(`${ind}}`); f(1); break;
      case 'loop':       emit(`${ind}while (true) {`); f(0); emit(`${ind}}`); f(1); break;
      case 'whileloop':  emit(`${ind}while (${g(1)}) {`); f(0); emit(`${ind}}`); f(1); break;
      case 'forloop':    emit(`${ind}for (int ${v(2)} = (int)${g(1)}; ${v(2)} <= (int)${g(2)}; ${v(2)} += (int)${g(3)}) {`); f(0); emit(`${ind}}`); f(1); break;
      case 'branch':     emit(`${ind}if (${g(1)}) {`); f(0); emit(`${ind}} else {`); f(1); emit(`${ind}}`); break;
      case 'valswitch':  emit(`${ind}switch (${g(1)}) { case ${g(2)}: `); f(0); emit(`break; case ${g(3)}: `); f(1); emit(`break; default: `); f(3); emit('break; }'); break;
      // Math
      case 'add':       emit(`${ind}${v(0)} = ${g(0)} + ${g(1)};`); break;
      case 'subtract':  emit(`${ind}${v(0)} = ${g(0)} - ${g(1)};`); break;
      case 'multiply':  emit(`${ind}${v(0)} = ${g(0)} * ${g(1)};`); break;
      case 'divide':    emit(`${ind}${v(0)} = ${g(1)} != 0 ? ${g(0)} / ${g(1)} : 0f;`); break;
      case 'modulo':    emit(`${ind}${v(0)} = ${g(0)} % ${g(1)};`); break;
      case 'abs':       emit(`${ind}${v(0)} = Mathf.Abs(${g(0)});`); break;
      case 'clamp':     emit(`${ind}${v(0)} = Mathf.Clamp(${g(0)}, ${g(1)}, ${g(2)});`); break;
      case 'lerp':      emit(`${ind}${v(0)} = Mathf.Lerp(${g(0)}, ${g(1)}, ${g(2)});`); break;
      case 'round':     emit(`${ind}${v(0)} = Mathf.Round(${g(0)});`); break;
      case 'ceil':      emit(`${ind}${v(0)} = Mathf.Ceil(${g(0)});`); break;
      case 'floor':     emit(`${ind}${v(0)} = Mathf.Floor(${g(0)});`); break;
      case 'sin':       emit(`${ind}${v(0)} = Mathf.Sin(${g(0)});`); break;
      case 'cos':       emit(`${ind}${v(0)} = Mathf.Cos(${g(0)});`); break;
      case 'tan':       emit(`${ind}${v(0)} = Mathf.Tan(${g(0)});`); break;
      case 'asin':      emit(`${ind}${v(0)} = Mathf.Asin(${g(0)});`); break;
      case 'acos':      emit(`${ind}${v(0)} = Mathf.Acos(${g(0)});`); break;
      case 'atan2':     emit(`${ind}${v(0)} = Mathf.Atan2(${g(0)}, ${g(1)});`); break;
      case 'min':       emit(`${ind}${v(0)} = Mathf.Min(${g(0)}, ${g(1)});`); break;
      case 'max':       emit(`${ind}${v(0)} = Mathf.Max(${g(0)}, ${g(1)});`); break;
      case 'power':     emit(`${ind}${v(0)} = Mathf.Pow(${g(0)}, ${g(1)});`); break;
      case 'sqrt':      emit(`${ind}${v(0)} = Mathf.Sqrt(${g(0)});`); break;
      case 'randnum':   emit(`${ind}${v(0)} = UnityEngine.Random.Range(${g(0)}, ${g(1)});`); break;
      case 'randint':   emit(`${ind}${v(0)} = UnityEngine.Random.Range((int)${g(0)}, (int)${g(1)} + 1);`); break;
      // Logic
      case 'and':       emit(`${ind}${v(0)} = ${g(0)} && ${g(1)};`); break;
      case 'or':        emit(`${ind}${v(0)} = ${g(0)} || ${g(1)};`); break;
      case 'not':       emit(`${ind}${v(0)} = !${g(0)};`); break;
      case 'nand':      emit(`${ind}${v(0)} = !(${g(0)} && ${g(1)});`); break;
      case 'nor':       emit(`${ind}${v(0)} = !(${g(0)} || ${g(1)});`); break;
      case 'xor':       emit(`${ind}${v(0)} = ${g(0)} ^ ${g(1)};`); break;
      case 'eq':        emit(`${ind}${v(0)} = Equals(${g(0)}, ${g(1)});`); break;
      case 'gt':        emit(`${ind}${v(0)} = ${g(0)} > ${g(1)};`); break;
      case 'lt':        emit(`${ind}${v(0)} = ${g(0)} < ${g(1)};`); break;
      case 'gte':       emit(`${ind}${v(0)} = ${g(0)} >= ${g(1)};`); break;
      case 'lte':       emit(`${ind}${v(0)} = ${g(0)} <= ${g(1)};`); break;
      case 'notEq':     emit(`${ind}${v(0)} = !Equals(${g(0)}, ${g(1)});`); break;
      // Variables
      case 'var_int': case 'var_float': case 'var_bool': case 'var_string':
      case 'var_player': case 'var_vec3': case 'var_quat': case 'var_color':
      case 'var_cloud': case 'var_synced':
        const vname = node.varName || 'myVar';
        emit(`${ind}${vname} = ${g(1)};`); f(0); emit(`${ind}${v(1)} = ${vname};`); break;
      // Lists
      case 'list_add':      emit(`${ind}${g(1)}.Add(${g(2)});`); f(0); break;
      case 'list_remove':   emit(`${ind}${g(1)}.RemoveAt((int)${g(2)});`); f(0); break;
      case 'list_get':      emit(`${ind}${v(0)} = ${g(0)}[(int)${g(1)}];`); break;
      case 'list_contains': emit(`${ind}${v(0)} = ${g(0)}.Contains(${g(1)});`); break;
      case 'list_count':    emit(`${ind}${v(0)} = ${g(0)}.Count;`); break;
      // Events
      case 'evt_send':      emit(`${ind}// Send event with args: ${g(1)}, ${g(2)}, ${g(3)}`); f(0); break;
      // Player
      case 'pl_name':       emit(`${ind}${v(0)} = ${g(0)}.name;`); break;
      case 'pl_getpos':     emit(`${ind}${v(0)} = ${g(0)}.transform.position;`); break;
      case 'pl_setvel':     emit(`${ind}${g(0)}.GetComponent<Rigidbody>().velocity = ${g(1)};`); f(0); break;
      case 'pl_teleport':   emit(`${ind}${g(0)}.transform.position = ${g(1)};`); f(0); break;
      case 'pl_local':      emit(`${ind}${v(0)} = /* LocalPlayer */;`); break;
      // UI
      case 'ui_notify':     emit(`${ind}Debug.Log($"[Notify {${g(1)}}]: {${g(2)}}");`); f(0); break;
      case 'ui_subtitle':   emit(`${ind}// Show subtitle: ${g(2)}`); f(0); break;
      case 'ui_settext':    emit(`${ind}${g(0)}.GetComponent<TMPro.TextMeshPro>().text = ${g(1)};`); f(0); break;
      // Objects
      case 'obj_getpos':    emit(`${ind}${v(0)} = ${g(0)}.transform.position;`); break;
      case 'obj_setpos':    emit(`${ind}${g(0)}.transform.position = ${g(1)};`); f(0); break;
      case 'obj_destroy':   emit(`${ind}Destroy(${g(0)});`); f(0); break;
      case 'obj_setactive': emit(`${ind}${g(0)}.SetActive(${g(1)});`); f(0); break;
      case 'obj_instantiate': emit(`${ind}${v(1)} = Instantiate(${g(1)}, ${g(2)}, ${g(3)});`); f(0); break;
      // Combatant
      case 'cmb_gethealth': emit(`${ind}${v(0)} = /* ${g(0)}.Health */;`); break;
      case 'cmb_sethealth': emit(`${ind}/* ${g(0)}.Health = ${g(1)}; */`); f(0); break;
      case 'cmb_damage':    emit(`${ind}/* ${g(0)}.TakeDamage(${g(1)}); */`); f(0); break;
      case 'cmb_isalive':   emit(`${ind}${v(0)} = /* ${g(0)}.IsAlive */;`); break;
      // Gadgets
      case 'anim_play':     emit(`${ind}${g(0)}.GetComponent<Animator>().Play(${g(1)});`); f(0); break;
      case 'anim_stop':     emit(`${ind}${g(0)}.GetComponent<Animator>().StopPlayback();`); f(0); break;
      case 'audio_play':    emit(`${ind}${g(0)}.GetComponent<AudioSource>().Play();`); f(0); break;
      case 'audio_vol':     emit(`${ind}${g(0)}.GetComponent<AudioSource>().volume = ${g(1)};`); f(0); break;
      case 'light_color':   emit(`${ind}${g(0)}.GetComponent<Light>().color = ${g(1)};`); f(0); break;
      case 'light_int':     emit(`${ind}${g(0)}.GetComponent<Light>().intensity = ${g(1)};`); f(0); break;
      case 'emitter_start': emit(`${ind}${g(0)}.GetComponent<ParticleSystem>().Play();`); f(0); break;
      case 'emitter_stop':  emit(`${ind}${g(0)}.GetComponent<ParticleSystem>().Stop();`); f(0); break;
      // Conversion
      case 'to_string':   emit(`${ind}${v(0)} = ${g(0)}.ToString();`); break;
      case 'parse_int':   emit(`${ind}${v(1)} = int.TryParse(${g(0)}, out int _pi) ? _pi : 0; ${v(1)} = _pi; ${v(2)} = true;`); break;
      case 'parse_float': emit(`${ind}${v(1)} = float.TryParse(${g(0)}, out float _pf) ? _pf : 0f;`); break;
      case 'vec3_make':   emit(`${ind}${v(0)} = new Vector3(${g(0)}, ${g(1)}, ${g(2)});`); break;
      case 'vec3_split':  emit(`${ind}${v(0)} = ${g(0)}.x; ${v(1)} = ${g(0)}.y; ${v(2)} = ${g(0)}.z;`); break;
      case 'color_make':  emit(`${ind}${v(0)} = new Color(${g(0)}, ${g(1)}, ${g(2)}, ${g(3)});`); break;
      default: emit(`${ind}// [${def.name}] — not yet mapped`); break;
    }
  }

  // ═══════════════════════ LUA ═══════════════════════════
  function toLua(ctx) {
    const lines = []; const o = s => lines.push(s);
    o('-- Generated by RR Circuits'); o('-- Language: Lua (Roblox)'); o('');
    Object.values(ctx.vars).forEach(v => { o(`local ${v.name} = ${luaDef(v.type)}`); });
    ctx.nodes.forEach(({ id, chipId }) => {
      const d = getChipDef(chipId); if(!d) return;
      d.outputs.forEach((p,i) => { if(p.type!=='exec') o(`local ${varOf(id,i)} = ${luaDef(p.type)}`); });
    });
    o('');
    ctx.entries.forEach(node => {
      const d = getChipDef(node.chipId);
      o(`local function ${luaEv(node.chipId)}()`);
      emitLua(ctx, node.id, '    ', o);
      o('end'); o('');
    });
    if (!ctx.entries.length) { o('local function main()'); ctx.nodes.forEach(n => emitLua(ctx, n.id,'    ',o)); o('end'); o('main()'); }
    return lines.join('\n');
  }

  function luaDef(t) { return {bool:'false',int:'0',float:'0',number:'0',string:'""',list:'{}'}[t]||'nil'; }
  function luaEv(id) { return {on_init:'onInit',on_update:'onUpdate',on_joined:'onPlayerJoined',on_left:'onPlayerLeft'}[id]||id; }

  function emitLua(ctx, nodeId, ind, o) {
    const { node, def } = ctx.defs[nodeId]; if (!def) return;
    const g = i => getExpr(ctx, nodeId, i, 'lua');
    const v = i => varOf(nodeId, i);
    const f = (p) => follow(ctx, nodeId, p, 'lua', ind, o, emitLua);

    switch (node.chipId) {
      case 'authority': o(`${ind}if isLocalAuthority() then`); f(0); o(`${ind}else`); f(1); o(`${ind}end`); break;
      case 'sequence':  f(0); f(1); f(2); f(3); f(4); break;
      case 'delay':     o(`${ind}task.wait(${g(1)})`); f(0); break;
      case 'foreach':   o(`${ind}for i, _item in ipairs(${g(1)}) do`); o(`${ind}    local ${v(2)} = _item`); f(0); o(`${ind}end`); f(1); break;
      case 'loop':      o(`${ind}while true do`); f(0); o(`${ind}end`); break;
      case 'whileloop': o(`${ind}while ${g(1)} do`); f(0); o(`${ind}end`); f(1); break;
      case 'forloop':   o(`${ind}for ${v(2)} = ${g(1)}, ${g(2)}, ${g(3)} do`); f(0); o(`${ind}end`); f(1); break;
      case 'branch':    o(`${ind}if ${g(1)} then`); f(0); o(`${ind}else`); f(1); o(`${ind}end`); break;
      case 'add':       o(`${ind}${v(0)} = ${g(0)} + ${g(1)}`); break;
      case 'subtract':  o(`${ind}${v(0)} = ${g(0)} - ${g(1)}`); break;
      case 'multiply':  o(`${ind}${v(0)} = ${g(0)} * ${g(1)}`); break;
      case 'divide':    o(`${ind}${v(0)} = ${g(0)} / ${g(1)}`); break;
      case 'modulo':    o(`${ind}${v(0)} = ${g(0)} % ${g(1)}`); break;
      case 'abs':       o(`${ind}${v(0)} = math.abs(${g(0)})`); break;
      case 'clamp':     o(`${ind}${v(0)} = math.clamp(${g(0)}, ${g(1)}, ${g(2)})`); break;
      case 'lerp':      o(`${ind}${v(0)} = ${g(0)} + (${g(1)} - ${g(0)}) * ${g(2)}`); break;
      case 'round':     o(`${ind}${v(0)} = math.round(${g(0)})`); break;
      case 'floor':     o(`${ind}${v(0)} = math.floor(${g(0)})`); break;
      case 'ceil':      o(`${ind}${v(0)} = math.ceil(${g(0)})`); break;
      case 'sin':       o(`${ind}${v(0)} = math.sin(${g(0)})`); break;
      case 'cos':       o(`${ind}${v(0)} = math.cos(${g(0)})`); break;
      case 'tan':       o(`${ind}${v(0)} = math.tan(${g(0)})`); break;
      case 'and':       o(`${ind}${v(0)} = ${g(0)} and ${g(1)}`); break;
      case 'or':        o(`${ind}${v(0)} = ${g(0)} or ${g(1)}`); break;
      case 'not':       o(`${ind}${v(0)} = not ${g(0)}`); break;
      case 'eq':        o(`${ind}${v(0)} = ${g(0)} == ${g(1)}`); break;
      case 'gt':        o(`${ind}${v(0)} = ${g(0)} > ${g(1)}`); break;
      case 'lt':        o(`${ind}${v(0)} = ${g(0)} < ${g(1)}`); break;
      case 'to_string': o(`${ind}${v(0)} = tostring(${g(0)})`); break;
      case 'parse_int': o(`${ind}${v(0)} = math.floor(tonumber(${g(0)}) or 0)`); break;
      case 'vec3_make': o(`${ind}${v(0)} = Vector3.new(${g(0)}, ${g(1)}, ${g(2)})`); break;
      case 'vec3_split':o(`${ind}${v(0)} = ${g(0)}.X; ${v(1)} = ${g(0)}.Y; ${v(2)} = ${g(0)}.Z`); break;
      case 'randnum':   o(`${ind}${v(0)} = math.random() * (${g(1)} - ${g(0)}) + ${g(0)}`); break;
      case 'randint':   o(`${ind}${v(0)} = math.random(${g(0)}, ${g(1)})`); break;
      case 'var_int': case 'var_float': case 'var_bool': case 'var_string':
      case 'var_cloud': case 'var_synced': case 'var_vec3':
        o(`${ind}${node.varName||'myVar'} = ${g(1)}`); f(0); o(`${ind}${v(1)} = ${node.varName||'myVar'}`); break;
      case 'ui_notify':  o(`${ind}game:GetService("StarterGui"):SetCore("SendNotification", { Title="${g(2)}" })`); f(0); break;
      case 'pl_local':   o(`${ind}${v(0)} = game.Players.LocalPlayer`); break;
      case 'pl_getpos':  o(`${ind}${v(0)} = ${g(0)}.Character.HumanoidRootPart.Position`); break;
      case 'list_add':   o(`${ind}table.insert(${g(1)}, ${g(2)})`); f(0); break;
      case 'list_remove':o(`${ind}table.remove(${g(1)}, ${g(2)})`); f(0); break;
      case 'list_get':   o(`${ind}${v(0)} = ${g(0)}[${g(1)}+1]`); break;
      case 'list_count': o(`${ind}${v(0)} = #${g(0)}`); break;
      default: o(`${ind}-- [${def.name}]`); break;
    }
  }

  // ═══════════════════════ PYTHON ═══════════════════════════
  function toPython(ctx) {
    const lines = []; const o = s => lines.push(s);
    o('# Generated by RR Circuits'); o('import math, random'); o('');
    Object.values(ctx.vars).forEach(v => { o(`${v.name} = ${pyDef(v.type)}  # ${v.isCloud?'☁ Cloud':v.isSynced?'🔄 Synced':'Variable'}`); });
    ctx.nodes.forEach(({ id, chipId }) => {
      const d = getChipDef(chipId); if(!d) return;
      d.outputs.forEach((p,i) => { if(p.type!=='exec') o(`${varOf(id,i)} = ${pyDef(p.type)}`); });
    });
    o('');
    ctx.entries.forEach(node => {
      const d = getChipDef(node.chipId);
      o(`def ${pyEv(node.chipId)}():`);
      const body = []; emitPy(ctx, node.id, '    ', body);
      if (!body.length) body.push('    pass');
      body.forEach(l => o(l)); o('');
    });
    if (!ctx.entries.length) {
      o('def main():');
      const body = []; ctx.nodes.forEach(n => emitPy(ctx, n.id,'    ',body));
      if (!body.length) body.push('    pass');
      body.forEach(l => o(l)); o(''); o("if __name__ == '__main__': main()");
    }
    return lines.join('\n');
  }
  function pyDef(t) { return {bool:'False',int:'0',float:'0.0',number:'0',string:'""',list:'[]'}[t]||'None'; }
  function pyEv(id)  { return {on_init:'on_init',on_update:'on_update',on_joined:'on_player_joined',on_left:'on_player_left'}[id]||id; }

  function emitPy(ctx, nodeId, ind, lines) {
    const { node, def } = ctx.defs[nodeId]; if (!def) return;
    const o = s => lines.push(s);
    const g = i => getExpr(ctx, nodeId, i, 'python');
    const v = i => varOf(nodeId, i);
    const f = (p, extraInd='') => follow(ctx, nodeId, p, 'python', ind+extraInd, {push:s=>lines.push(s)}, emitPy);
    const fLines = (p, extraInd) => { const tmp=[]; follow(ctx,nodeId,p,'python',ind+extraInd,tmp,emitPy); return tmp; };

    function ifBlock(cond, thenPort, elsePort) {
      o(`${ind}if ${cond}:`);
      const thenL = fLines(thenPort,'    '); if (!thenL.length) thenL.push(`${ind}    pass`); thenL.forEach(l=>o(l));
      const elseL = fLines(elsePort,'    ');
      if (elseL.length) { o(`${ind}else:`); elseL.forEach(l=>o(l)); }
    }

    switch (node.chipId) {
      case 'authority': ifBlock('is_local_authority()', 0, 1); break;
      case 'sequence':  [0,1,2,3,4].forEach(i=>f(i)); break;
      case 'delay':     o(`${ind}import time; time.sleep(${g(1)})`); f(0); break;
      case 'foreach':   o(`${ind}for _i, _item in enumerate(${g(1)}):`); o(`${ind}    ${v(2)} = _item`);
                        const fl=fLines(0,'    '); if(!fl.length) fl.push(`${ind}    pass`); fl.forEach(l=>o(l)); f(1); break;
      case 'loop':      o(`${ind}while True:`); const lp=fLines(0,'    '); if(!lp.length) lp.push(`${ind}    pass`); lp.forEach(l=>o(l)); break;
      case 'whileloop': o(`${ind}while ${g(1)}:`); const wl=fLines(0,'    '); if(!wl.length) wl.push(`${ind}    pass`); wl.forEach(l=>o(l)); f(1); break;
      case 'forloop':   o(`${ind}for ${v(2)} in range(int(${g(1)}), int(${g(2)})+1, max(1,int(${g(3)}))):`);
                        const fl2=fLines(0,'    '); if(!fl2.length) fl2.push(`${ind}    pass`); fl2.forEach(l=>o(l)); f(1); break;
      case 'branch':    ifBlock(g(1), 0, 1); break;
      case 'add':       o(`${ind}${v(0)} = ${g(0)} + ${g(1)}`); break;
      case 'subtract':  o(`${ind}${v(0)} = ${g(0)} - ${g(1)}`); break;
      case 'multiply':  o(`${ind}${v(0)} = ${g(0)} * ${g(1)}`); break;
      case 'divide':    o(`${ind}${v(0)} = ${g(0)} / ${g(1)} if ${g(1)} != 0 else 0`); break;
      case 'modulo':    o(`${ind}${v(0)} = ${g(0)} % ${g(1)}`); break;
      case 'abs':       o(`${ind}${v(0)} = abs(${g(0)})`); break;
      case 'clamp':     o(`${ind}${v(0)} = max(${g(1)}, min(${g(2)}, ${g(0)}))`); break;
      case 'lerp':      o(`${ind}${v(0)} = ${g(0)} + (${g(1)} - ${g(0)}) * ${g(2)}`); break;
      case 'round':     o(`${ind}${v(0)} = round(${g(0)})`); break;
      case 'floor':     o(`${ind}${v(0)} = math.floor(${g(0)})`); break;
      case 'ceil':      o(`${ind}${v(0)} = math.ceil(${g(0)})`); break;
      case 'sin':       o(`${ind}${v(0)} = math.sin(${g(0)})`); break;
      case 'cos':       o(`${ind}${v(0)} = math.cos(${g(0)})`); break;
      case 'tan':       o(`${ind}${v(0)} = math.tan(${g(0)})`); break;
      case 'and':       o(`${ind}${v(0)} = ${g(0)} and ${g(1)}`); break;
      case 'or':        o(`${ind}${v(0)} = ${g(0)} or ${g(1)}`); break;
      case 'not':       o(`${ind}${v(0)} = not ${g(0)}`); break;
      case 'eq':        o(`${ind}${v(0)} = ${g(0)} == ${g(1)}`); break;
      case 'gt':        o(`${ind}${v(0)} = ${g(0)} > ${g(1)}`); break;
      case 'lt':        o(`${ind}${v(0)} = ${g(0)} < ${g(1)}`); break;
      case 'to_string': o(`${ind}${v(0)} = str(${g(0)})`); break;
      case 'parse_int': o(`${ind}${v(0)} = int(${g(0)}) if str(${g(0)}).lstrip('-').isdigit() else 0`); break;
      case 'vec3_make': o(`${ind}${v(0)} = (${g(0)}, ${g(1)}, ${g(2)})`); break;
      case 'vec3_split':o(`${ind}${v(0)}, ${v(1)}, ${v(2)} = ${g(0)}`); break;
      case 'randnum':   o(`${ind}${v(0)} = random.uniform(${g(0)}, ${g(1)})`); break;
      case 'randint':   o(`${ind}${v(0)} = random.randint(int(${g(0)}), int(${g(1)}))`); break;
      case 'var_int': case 'var_float': case 'var_bool': case 'var_string':
      case 'var_cloud': case 'var_synced': case 'var_vec3':
        o(`${ind}global ${node.varName||'my_var'}`); o(`${ind}${node.varName||'my_var'} = ${g(1)}`); f(0); o(`${ind}${v(1)} = ${node.varName||'my_var'}`); break;
      case 'ui_notify':  o(`${ind}print(f"[Notify]: {${g(2)}}")`); f(0); break;
      case 'pl_local':   o(`${ind}${v(0)} = get_local_player()`); break;
      case 'list_add':   o(`${ind}${g(1)}.append(${g(2)})`); f(0); break;
      case 'list_remove':o(`${ind}${g(1)}.pop(int(${g(2)}))`); f(0); break;
      case 'list_get':   o(`${ind}${v(0)} = ${g(0)}[int(${g(1)})]`); break;
      case 'list_count': o(`${ind}${v(0)} = len(${g(0)})`); break;
      default: o(`${ind}# [${def.name}]`); break;
    }
  }

  // ═══════════════════════ JavaScript ═══════════════════════════
  function toJS(ctx) {
    const lines = []; const o = s => lines.push(s);
    o('// Generated by RR Circuits'); o('// Language: JavaScript'); o('');
    Object.values(ctx.vars).forEach(v => { o(`let ${v.name} = ${jsDef(v.type)}; // ${v.isCloud?'☁ Cloud':v.isSynced?'🔄 Synced':'Variable'}`); });
    ctx.nodes.forEach(({ id, chipId }) => {
      const d = getChipDef(chipId); if(!d) return;
      d.outputs.forEach((p,i) => { if(p.type!=='exec') o(`let ${varOf(id,i)} = ${jsDef(p.type)};`); });
    });
    o('');
    ctx.entries.forEach(node => {
      o(`function ${jsEv(node.chipId)}() {`);
      emitJS(ctx, node.id, '    ', o); o('}'); o('');
    });
    if (!ctx.entries.length) { o('function main() {'); ctx.nodes.forEach(n=>emitJS(ctx,n.id,'    ',o)); o('}'); o('main();'); }
    return lines.join('\n');
  }
  function jsDef(t) { return {bool:'false',int:'0',float:'0',number:'0',string:'""',list:'[]'}[t]||'null'; }
  function jsEv(id)  { return {on_init:'onInit',on_update:'onUpdate',on_joined:'onPlayerJoined',on_left:'onPlayerLeft'}[id]||id; }

  function emitJS(ctx, nodeId, ind, o) {
    const { node, def } = ctx.defs[nodeId]; if (!def) return;
    const g = i => getExpr(ctx, nodeId, i, 'javascript');
    const v = i => varOf(nodeId, i);
    const f = (p) => follow(ctx, nodeId, p, 'javascript', ind, o, emitJS);
    switch (node.chipId) {
      case 'add':       o(`${ind}${v(0)} = ${g(0)} + ${g(1)};`); break;
      case 'subtract':  o(`${ind}${v(0)} = ${g(0)} - ${g(1)};`); break;
      case 'multiply':  o(`${ind}${v(0)} = ${g(0)} * ${g(1)};`); break;
      case 'divide':    o(`${ind}${v(0)} = ${g(1)} !== 0 ? ${g(0)} / ${g(1)} : 0;`); break;
      case 'modulo':    o(`${ind}${v(0)} = ${g(0)} % ${g(1)};`); break;
      case 'floor':     o(`${ind}${v(0)} = Math.floor(${g(0)});`); break;
      case 'ceil':      o(`${ind}${v(0)} = Math.ceil(${g(0)});`); break;
      case 'round':     o(`${ind}${v(0)} = Math.round(${g(0)});`); break;
      case 'abs':       o(`${ind}${v(0)} = Math.abs(${g(0)});`); break;
      case 'clamp':     o(`${ind}${v(0)} = Math.max(${g(1)}, Math.min(${g(2)}, ${g(0)}));`); break;
      case 'lerp':      o(`${ind}${v(0)} = ${g(0)} + (${g(1)} - ${g(0)}) * ${g(2)};`); break;
      case 'sin':       o(`${ind}${v(0)} = Math.sin(${g(0)});`); break;
      case 'cos':       o(`${ind}${v(0)} = Math.cos(${g(0)});`); break;
      case 'tan':       o(`${ind}${v(0)} = Math.tan(${g(0)});`); break;
      case 'and':       o(`${ind}${v(0)} = ${g(0)} && ${g(1)};`); break;
      case 'or':        o(`${ind}${v(0)} = ${g(0)} || ${g(1)};`); break;
      case 'not':       o(`${ind}${v(0)} = !${g(0)};`); break;
      case 'eq':        o(`${ind}${v(0)} = ${g(0)} === ${g(1)};`); break;
      case 'gt':        o(`${ind}${v(0)} = ${g(0)} > ${g(1)};`); break;
      case 'lt':        o(`${ind}${v(0)} = ${g(0)} < ${g(1)};`); break;
      case 'randnum':   o(`${ind}${v(0)} = Math.random() * (${g(1)} - ${g(0)}) + ${g(0)};`); break;
      case 'randint':   o(`${ind}${v(0)} = Math.floor(Math.random()*(${g(1)}-${g(0)}+1))+${g(0)};`); break;
      case 'to_string': o(`${ind}${v(0)} = String(${g(0)});`); break;
      case 'parse_int': o(`${ind}${v(0)} = parseInt(${g(0)}) || 0;`); break;
      case 'vec3_make': o(`${ind}${v(0)} = {x:${g(0)}, y:${g(1)}, z:${g(2)}};`); break;
      case 'branch':    o(`${ind}if (${g(1)}) {`); f(0); o(`${ind}} else {`); f(1); o(`${ind}}`); break;
      case 'forloop':   o(`${ind}for (let ${v(2)}=${g(1)};${v(2)}<=${g(2)};${v(2)}+=${g(3)}) {`); f(0); o(`${ind}}`); f(1); break;
      case 'foreach':   o(`${ind}${g(1)}.forEach((_item,_i) => { let ${v(2)}=_item;`); f(0); o(`${ind}});`); f(1); break;
      case 'var_int': case 'var_float': case 'var_bool': case 'var_string':
      case 'var_cloud': case 'var_synced':
        o(`${ind}${node.varName||'myVar'} = ${g(1)};`); f(0); o(`${ind}${v(1)} = ${node.varName||'myVar'};`); break;
      case 'list_add':   o(`${ind}${g(1)}.push(${g(2)});`); f(0); break;
      case 'list_count': o(`${ind}${v(0)} = ${g(0)}.length;`); break;
      case 'ui_notify':  o(`${ind}console.log('[Notify]:', ${g(2)});`); f(0); break;
      default: o(`${ind}// [${def.name}]`); break;
    }
  }

  // ═══════════════════════ GDScript ═══════════════════════════
  function toGDS(ctx) {
    const lines = []; const o = s => lines.push(s);
    o('# Generated by RR Circuits'); o('# Language: GDScript (Godot 4)'); o('extends Node'); o('');
    Object.values(ctx.vars).forEach(v => { o(`var ${v.name} = ${gdsDef(v.type)}`); });
    ctx.nodes.forEach(({ id, chipId }) => {
      const d = getChipDef(chipId); if(!d) return;
      d.outputs.forEach((p,i) => { if(p.type!=='exec') o(`var ${varOf(id,i)} = ${gdsDef(p.type)}`); });
    });
    o('');
    ctx.entries.forEach(node => {
      o(`func ${gdsEv(node.chipId)}():`);
      const body=[]; emitGDS(ctx,node.id,'\t',body);
      if(!body.length) body.push('\tpass');
      body.forEach(l=>o(l)); o('');
    });
    if (!ctx.entries.length) { o('func _ready():'); const b=[]; ctx.nodes.forEach(n=>emitGDS(ctx,n.id,'\t',b)); if(!b.length) b.push('\tpass'); b.forEach(l=>o(l)); }
    return lines.join('\n');
  }
  function gdsDef(t) { return {bool:'false',int:'0',float:'0.0',number:'0',string:'""',vector3:'Vector3.ZERO',quaternion:'Quaternion.IDENTITY',list:'[]'}[t]||'null'; }
  function gdsEv(id) { return {on_init:'_ready',on_update:'_process',on_joined:'_on_player_joined',on_left:'_on_player_left'}[id]||id; }

  function emitGDS(ctx, nodeId, ind, lines) {
    const { node, def } = ctx.defs[nodeId]; if (!def) return;
    const o = s => lines.push(s);
    const g = i => getExpr(ctx, nodeId, i, 'gdscript');
    const v = i => varOf(nodeId, i);
    const f = (p) => follow(ctx, nodeId, p, 'gdscript', ind, lines, emitGDS);
    switch (node.chipId) {
      case 'add':    o(`${ind}${v(0)} = ${g(0)} + ${g(1)}`); break;
      case 'subtract':o(`${ind}${v(0)} = ${g(0)} - ${g(1)}`); break;
      case 'multiply':o(`${ind}${v(0)} = ${g(0)} * ${g(1)}`); break;
      case 'divide': o(`${ind}${v(0)} = ${g(0)} / ${g(1)} if ${g(1)} != 0 else 0`); break;
      case 'floor':  o(`${ind}${v(0)} = floor(${g(0)})`); break;
      case 'ceil':   o(`${ind}${v(0)} = ceil(${g(0)})`); break;
      case 'round':  o(`${ind}${v(0)} = round(${g(0)})`); break;
      case 'abs':    o(`${ind}${v(0)} = abs(${g(0)})`); break;
      case 'clamp':  o(`${ind}${v(0)} = clamp(${g(0)}, ${g(1)}, ${g(2)})`); break;
      case 'lerp':   o(`${ind}${v(0)} = lerp(${g(0)}, ${g(1)}, ${g(2)})`); break;
      case 'sin':    o(`${ind}${v(0)} = sin(${g(0)})`); break;
      case 'cos':    o(`${ind}${v(0)} = cos(${g(0)})`); break;
      case 'and':    o(`${ind}${v(0)} = ${g(0)} and ${g(1)}`); break;
      case 'or':     o(`${ind}${v(0)} = ${g(0)} or ${g(1)}`); break;
      case 'not':    o(`${ind}${v(0)} = not ${g(0)}`); break;
      case 'branch': o(`${ind}if ${g(1)}:`); f(0); o(`${ind}else:`); f(1); break;
      case 'vec3_make': o(`${ind}${v(0)} = Vector3(${g(0)}, ${g(1)}, ${g(2)})`); break;
      case 'to_string': o(`${ind}${v(0)} = str(${g(0)})`); break;
      case 'randnum':   o(`${ind}${v(0)} = randf_range(${g(0)}, ${g(1)})`); break;
      case 'randint':   o(`${ind}${v(0)} = randi_range(int(${g(0)}), int(${g(1)}))`); break;
      default: o(`${ind}# [${def.name}]`); break;
    }
  }

  // ═══════════════════════ Pseudocode ═══════════════════════════
  function toPseudo(ctx) {
    const lines = []; const o = s => lines.push(s);
    o('// Generated by RR Circuits'); o('// PSEUDOCODE'); o('');
    ctx.entries.forEach(node => {
      const d = getChipDef(node.chipId);
      o(`EVENT ${d?.name||node.chipId.toUpperCase()}:`);
      emitPseudo(ctx, node.id, '    ', o); o('END EVENT'); o('');
    });
    if (!ctx.entries.length) { o('PROGRAM:'); ctx.nodes.forEach(n=>emitPseudo(ctx,n.id,'    ',o)); o('END PROGRAM'); }
    return lines.join('\n');
  }

  function emitPseudo(ctx, nodeId, ind, o) {
    const { node, def } = ctx.defs[nodeId]; if (!def) return;
    const g = i => getExpr(ctx, nodeId, i, 'pseudocode');
    const v = i => varOf(nodeId, i);
    const f = (p,ei='') => follow(ctx, nodeId, p, 'pseudocode', ind+ei, o, emitPseudo);
    switch (node.chipId) {
      case 'authority': o(`${ind}IF IS LOCAL AUTHORITY THEN`); f(0,'    '); o(`${ind}ELSE`); f(1,'    '); o(`${ind}END IF`); break;
      case 'branch':    o(`${ind}IF ${g(1)} THEN`); f(0,'    '); o(`${ind}ELSE`); f(1,'    '); o(`${ind}END IF`); break;
      case 'sequence':  o(`${ind}SEQUENCE:`); [0,1,2,3,4].forEach(i=>f(i,'  ')); o(`${ind}END SEQUENCE`); break;
      case 'delay':     o(`${ind}WAIT ${g(1)} SECONDS`); f(0); break;
      case 'forloop':   o(`${ind}FOR index FROM ${g(1)} TO ${g(2)} STEP ${g(3)}`); f(0,'    '); o(`${ind}END FOR`); f(1); break;
      case 'foreach':   o(`${ind}FOR EACH item IN ${g(1)}`); f(0,'    '); o(`${ind}END FOR EACH`); f(1); break;
      case 'whileloop': o(`${ind}WHILE ${g(1)}`); f(0,'    '); o(`${ind}END WHILE`); f(1); break;
      case 'add':       o(`${ind}${v(0)} ← ${g(0)} + ${g(1)}`); break;
      case 'subtract':  o(`${ind}${v(0)} ← ${g(0)} − ${g(1)}`); break;
      case 'multiply':  o(`${ind}${v(0)} ← ${g(0)} × ${g(1)}`); break;
      case 'divide':    o(`${ind}${v(0)} ← ${g(0)} ÷ ${g(1)}`); break;
      case 'and':       o(`${ind}${v(0)} ← ${g(0)} AND ${g(1)}`); break;
      case 'or':        o(`${ind}${v(0)} ← ${g(0)} OR ${g(1)}`); break;
      case 'not':       o(`${ind}${v(0)} ← NOT ${g(0)}`); break;
      case 'ui_notify': o(`${ind}SHOW NOTIFICATION TO ${g(1)}: "${g(2)}"`); f(0); break;
      case 'pl_name':   o(`${ind}${v(0)} ← NAME OF ${g(0)}`); break;
      case 'var_int': case 'var_float': case 'var_bool': case 'var_string':
      case 'var_cloud': case 'var_synced':
        o(`${ind}SET ${node.varName||'myVar'} ← ${g(1)}`); f(0); break;
      default:          o(`${ind}[${def.name}](${def.inputs.map((_,i)=>g(i)).join(', ')})`); break;
    }
  }

  // ═══════════════════════ ROBLOX STUDIO (Lua) ═══════════════════════
  function toRoblox(ctx) {
    const lines = []; const o = s => lines.push(s);
    o('-- Generated by RR Circuits for Roblox Studio');
    o('-- Drop this Script into ServerScriptService');
    o('');
    o('local Players = game:GetService("Players")');
    o('local RunService = game:GetService("RunService")');
    o('local ReplicatedStorage = game:GetService("ReplicatedStorage")');

    // Cloud variables use DataStore
    const hasCloud = Object.values(ctx.vars).some(v => v.isCloud);
    if (hasCloud) {
      o('local DataStoreService = game:GetService("DataStoreService")');
      o('local DataStore = DataStoreService:GetDataStore("RRCircuitsData")');
    }
    o('');

    // Variable declarations
    Object.values(ctx.vars).forEach(v => {
      if (v.isCloud) {
        o(`-- ☁ Cloud Variable: ${v.name} (persists via DataStore)`);
        o(`local ${v.name} = DataStore:GetAsync("${v.name}") or ${luaDef(v.type)}`);
      } else if (v.isSynced) {
        o(`-- 🔄 Synced Variable: ${v.name} (use RemoteEvents for replication)`);
        o(`local ${v.name} = ${luaDef(v.type)}`);
        o(`local ${v.name}Remote = ReplicatedStorage:FindFirstChild("${v.name}Sync") or Instance.new("RemoteEvent", ReplicatedStorage)`);
        o(`${v.name}Remote.Name = "${v.name}Sync"`);
      } else {
        o(`local ${v.name} = ${luaDef(v.type)}`);
      }
    });
    o('');

    // Output vars
    ctx.nodes.forEach(({ id, chipId }) => {
      const d = getChipDef(chipId); if (!d) return;
      d.outputs.forEach((p, i) => { if (p.type !== 'exec') o(`local ${varOf(id,i)} = ${luaDef(p.type)}`); });
    });
    o('');

    // Event handlers
    ctx.entries.forEach(node => {
      const d = getChipDef(node.chipId);
      if (node.chipId === 'on_joined') {
        o('Players.PlayerAdded:Connect(function(player)');
        emitLua(ctx, node.id, '    ', o);
        o('end)');
      } else if (node.chipId === 'on_left') {
        o('Players.PlayerRemoving:Connect(function(player)');
        emitLua(ctx, node.id, '    ', o);
        o('end)');
      } else if (node.chipId === 'on_update') {
        o('RunService.Heartbeat:Connect(function(deltaTime)');
        emitLua(ctx, node.id, '    ', o);
        o('end)');
      } else if (node.chipId === 'on_init') {
        o('-- On Init');
        emitLua(ctx, node.id, '', o);
      } else {
        o(`local function ${luaEv(node.chipId)}()`);
        emitLua(ctx, node.id, '    ', o);
        o('end');
      }
      o('');
    });

    if (!ctx.entries.length) {
      o('-- Main'); ctx.nodes.forEach(n => emitLua(ctx, n.id, '', o));
    }
    return lines.join('\n');
  }

  // ═══════════════════════ UNITY C# ═══════════════════════
  function toUnity(ctx) {
    const lines = []; const o = s => lines.push(s);
    const projName = document.getElementById('projectName')?.textContent.trim().replace(/\s+/g,'') || 'GeneratedCircuit';
    o('// Generated by RR Circuits for Unity');
    o('// Attach to a GameObject in your scene');
    o('');
    o('using System.Collections;');
    o('using System.Collections.Generic;');
    o('using UnityEngine;');
    o('');

    // If cloud vars, add PlayerPrefs usage
    const hasCloud  = Object.values(ctx.vars).some(v => v.isCloud);
    const hasSynced = Object.values(ctx.vars).some(v => v.isSynced);
    if (hasCloud)  { o('// ☁ Cloud Variables use PlayerPrefs (or replace with your cloud save system)'); o(''); }
    if (hasSynced) { o('// 🔄 Synced Variables — requires Netcode for GameObjects or Mirror'); o(''); }

    o(`[AddComponentMenu("RR Circuits/${projName}")]`);
    o(`public class ${projName} : MonoBehaviour`);
    o('{');

    // Variable fields
    Object.values(ctx.vars).forEach(v => {
      if (v.isCloud)  o(`    // ☁ Cloud: loaded from PlayerPrefs`);
      if (v.isSynced) o(`    // 🔄 Synced: replicate via NetworkVariable`);
      o(`    private ${csType(v.type)} ${v.name} = ${csDefault(v.type)};`);
    });

    // Output vars
    ctx.nodes.forEach(({ id, chipId }) => {
      const d = getChipDef(chipId); if (!d) return;
      d.outputs.forEach((p, i) => { if (p.type !== 'exec') o(`    private ${csType(p.type)} ${varOf(id,i)};`); });
    });

    // Cloud var Awake loading
    if (hasCloud) {
      o('');
      o('    void Awake()');
      o('    {');
      Object.values(ctx.vars).filter(v => v.isCloud).forEach(v => {
        if (v.type === 'int')    o(`        ${v.name} = PlayerPrefs.GetInt("${v.name}", 0);`);
        else if (v.type === 'float') o(`        ${v.name} = PlayerPrefs.GetFloat("${v.name}", 0f);`);
        else                     o(`        ${v.name} = PlayerPrefs.GetString("${v.name}", "");`);
      });
      o('    }');
    }

    o('');
    ctx.entries.forEach(node => {
      o(`    ${csEvent(node.chipId)}`);
      o('    {');
      const emit = s => lines.push(s);
      emitCS(ctx, node.id, '        ', emit);
      o('    }');
      o('');
    });

    // Cloud save helper
    if (hasCloud) {
      o('    void SaveCloudVars()');
      o('    {');
      Object.values(ctx.vars).filter(v => v.isCloud).forEach(v => {
        if (v.type === 'int')    o(`        PlayerPrefs.SetInt("${v.name}", ${v.name});`);
        else if (v.type === 'float') o(`        PlayerPrefs.SetFloat("${v.name}", ${v.name});`);
        else                     o(`        PlayerPrefs.SetString("${v.name}", ${v.name});`);
      });
      o('        PlayerPrefs.Save();');
      o('    }');
    }

    o('}');
    return lines.join('\n');
  }

  // ═══════════════════════ UNREAL ENGINE C++ ═══════════════════════
  function toUnreal(ctx) {
    const lines = []; const o = s => lines.push(s);
    const projName = document.getElementById('projectName')?.textContent.trim().replace(/\s+/g,'') || 'GeneratedCircuit';
    o(`// Generated by RR Circuits for Unreal Engine 5`);
    o(`// Add ${projName}.h and ${projName}.cpp to your Source folder`);
    o('');
    o(`#include "${projName}.h"`);
    o('#include "Engine/Engine.h"');
    o('#include "GameFramework/Actor.h"');
    o('#include "Kismet/GameplayStatics.h"');
    o('');
    o(`A${projName}::A${projName}()`);
    o('{');
    o('    PrimaryActorTick.bCanEverTick = true;');
    o('}');
    o('');
    o(`void A${projName}::BeginPlay()`);
    o('{');
    o('    Super::BeginPlay();');
    // Init vars
    Object.values(ctx.vars).forEach(v => {
      if (v.isCloud)  o(`    // ☁ Cloud: use USaveGame or online subsystem for ${v.name}`);
      if (v.isSynced) o(`    // 🔄 Synced: use UPROPERTY(Replicated) for ${v.name}`);
    });
    // Entry nodes that fire on begin
    ctx.entries.filter(n => n.chipId === 'on_init').forEach(node => {
      emitCS(ctx, node.id, '    ', s => lines.push(s));
    });
    o('}');
    o('');
    o(`void A${projName}::Tick(float DeltaTime)`);
    o('{');
    o('    Super::Tick(DeltaTime);');
    ctx.entries.filter(n => n.chipId === 'on_update').forEach(node => {
      emitCS(ctx, node.id, '    ', s => lines.push(s));
    });
    o('}');
    o('');

    // Header file output as comment
    o('/* ── HEADER FILE (.h) ────────────────────────────────────────');
    o(`#pragma once`);
    o('#include "CoreMinimal.h"');
    o('#include "GameFramework/Actor.h"');
    o(`#include "${projName}.generated.h"`);
    o('');
    o('UCLASS()');
    o(`class YOURGAME_API A${projName} : public AActor`);
    o('{');
    o('    GENERATED_BODY()');
    o('public:');
    o(`    A${projName}();`);
    o('protected:');
    o('    virtual void BeginPlay() override;');
    o('public:');
    o('    virtual void Tick(float DeltaTime) override;');
    o('');
    Object.values(ctx.vars).forEach(v => {
      const uprop = v.isSynced ? 'UPROPERTY(Replicated, BlueprintReadWrite)' : 'UPROPERTY(BlueprintReadWrite)';
      o(`    ${uprop}`);
      o(`    ${unrealType(v.type)} ${v.name};`);
    });
    o('}; */');

    return lines.join('\n');
  }

  function unrealType(t) {
    return { int:'int32', float:'float', number:'float', bool:'bool', string:'FString',
             object:'AActor*', player:'APlayerController*', vector3:'FVector',
             quaternion:'FQuat', color_t:'FLinearColor', list:'TArray<UObject*>', any:'UObject*' }[t] || 'UObject*';
  }

  return { export: export_, fileExtension, engineInfo };
})();
